name: portfolio_website
description: A modern, professional portfolio website built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # UI & Animations
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Navigation & Routing
  go_router: ^13.0.0
  
  # Utilities
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  responsive_framework: ^1.1.1
  
  # Icons & Images
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.0
  
  # Performance
  flutter_cache_manager: ^3.3.1
  
  # 3D Effects
  flutter_3d_controller: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - lib/resources/